### ISSUE TITLE
ScrollView can host only one direct child

### ISSUE THREAD

**Issue by ArnyminerZ** [amarjain07/StickyScrollView#17]
I followed the sample code, and I got this error:
```
Caused by: android.view.InflateException: Binary XML file line #80 in com.arnyminerz.escalaralcoiaicomtat:layout/activity_area: ScrollView can host only one direct child
Caused by: java.lang.IllegalStateException: ScrollView can host only one direct child
   at android.widget.ScrollView.addView(ScrollView.java:379)
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
   at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
   at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
   at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
   at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
   at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
...
```

**Comment by amarjain07** [comment]
Updated the README file
