### ISSUE TITLE
is:issue is:open Sometimes I get crash when childs are using livedata observers

### ISSUE THREAD

**Issue by ghost** [amarjain07/StickyScrollView#25]
is:issue is:open Sometimes I get crash because typed array "android.content.res.TypedArray.getResourceId TypedArray.java"; It seems it's not working properly when child view are using livedata observers. 

android.content.res.TypedArray.getResourceId TypedArray.java:929
.StickyScrollView$a.onGlobalLayout SourceFile:1
android.view

Any Idea?

**Comment by sathishcse** [comment]
Cannot make calls to a recycled instance!
        at android.content.res.TypedArray.getResourceId(TypedArray.java:1128)
        at com.amar.library.provider.ResourceProvider.getResourceId(ResourceProvider.kt:13)
        at com.amar.library.ui.presenter.StickyScrollPresenter.onGlobalLayoutChange(StickyScrollPresenter.kt:31)
        at com.amar.library.ui.StickyScrollView$1.invoke(StickyScrollView.kt:37)
        at com.amar.library.ui.StickyScrollView$1.invoke(StickyScrollView.kt:36)
        at com.amar.library.ui.StickyScrollView$onLayoutUpdate$1.onGlobalLayout(StickyScrollView.kt:175)
        
        Above issue occurs in my project
